<a href="https://colab.research.google.com/github/ilkert08/numpy-tutorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2,3], [4,5,6]])

In [ ]:
# Get dimension
print(a.ndim)
print(b.ndim)


1
2


In [ ]:
# Get shape
print(a.shape) # 1 dimension
print(b.shape) # 2 dimension

(3,)
(2, 3)


In [ ]:
# Get type
print(a.dtype)
print(b.dtype)

int16
int64


In [ ]:
# Get item size
print(a.itemsize)
print(b.itemsize)

2
8


In [ ]:
# Get total size
print(a.nbytes)
print(b.nbytes)

6
48


# Acces / change

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
print(a.shape)

(2, 7)


In [ ]:
# Get a specific element [row, column]
print(a[1, 5])
print(a[1, -2])

13
13


In [ ]:
# Get a specific row
print(a[0, :])
print(a[1, :])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [ ]:
# Get a specific column
print(a[ : , 5])
print(a[ : , 6])

[ 6 13]
[ 7 14]


In [ ]:
#  arr[startindex : endindex : stepsize]
print(a[0, 1 : 6: 2])
print(a[0, 1 : 6: 1])

[2 4 6]
[2 3 4 5 6]


In [ ]:
# change

a[1,5] = 20
print(a)

a[:, 2] = 30
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2 30  4  5  6  7]
 [ 8  9 30 11 12 20 14]]


In [ ]:
# 3 - D example
b = np.array([[[1,2], [3, 4]], [[5,6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# access 3 - d list
print()
print(b[0, 1, 0])


3


In [ ]:
# Replace
b[:,1,:] = [[9,9], [1,1]] # Aynı shapede karşılık verirse hatasız atama yapar.
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [1 1]]]


In [ ]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4) # A arrayinnin shapeinde 4 lerden oluşan matris.

[[ 1  2 30  4  5  6  7]
 [ 8  9 30 11 12 20 14]]


In [ ]:
# Random decimal numbers
np.random.rand(4,2) # 0 ve 1 arasında 4x2 lik random matris.

array([[0.30130784, 0.88309998],
       [0.77007248, 0.40323034],
       [0.58695546, 0.67708656],
       [0.61737911, 0.79475215]])

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) # -4 ve 8 arasında 3x3'lük random matris.

array([[ 5, -1,  0],
       [ 0, -1,  1],
       [ 5,  0,  0]])

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0) # Her row'u 3 kez tekrar eder.
print(r1) 

print()
r1 = np.repeat(arr,3, axis=1) # Her column'u 3 kez tekrar eder.
print(r1) 

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1 2 2 2 3 3 3]]
